canonical: https://gematik.de/fhir/erp-servicerequest
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
FSHOnly: true
version: "1.1.0"
dependencies: # TODO Check dependencies
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.3.2
  de.gematik.erezept-workflow.r4: 1.2.x
  de.gematik.fhir.atf: 1.3.x
  kbv.basis: 1.3.x #TODO Check if this can be removed
  kbv.ita.for: 1.1.x
  kbv.ita.erp: 1.1.x
