canonical: https://gematik.de/fhir/erp-servicerequest
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
FSHOnly: true
version: "1.2.0-rc2"
dependencies:
  # basisprofile
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.0

  # gematik
  de.gematik.fhir.atf: 1.4.0-rc2
  de.gematik.fhir.directory: 0.11.12
  de.gematik.erezept-workflow.r4: 1.4.x
  de.gematik.epa: 1.1.0

  # kbv
  kbv.ita.erp: 1.1.x

  # secondary dependencies for the build process
  kbv.basis: 1.3.0
