canonical:  https://gematik.de/fhir/isik/v2/Basismodul
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden gematik-Basismodul Stufe 1 1.0.0
name: Implementierungsleitfaden gematik-Basismodul Stufe 1 1.0.0
status: active
version: # "1.0.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: info@gematik.de
dependencies:
  de.basisprofil.r4: 1.4.0
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1
  de.gematik.isik-medikation: 2.0.1
  kbv.ita.for: 1.1.0
  kbv.ita.erp: 1.1.0