canonical: https://gematik.de/fhir/erpmedreqcom
fhirVersion: 4.0.1
id: gematik.de.fhir.erpmedreqcom
name: Ressourcen zur Rezeptanforderung eines E-Rezeptes
status: draft
version: "1.0.0"
copyrightYear: 2022+
releaseLabel: draft
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: info@gematik.de
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.4.0
  de.gematik.erezept-workflow.r4: 1.2.0
  kbv.basis: 1.3.0
  kbv.ita.for: 1.1.0
  kbv.ita.erp: 1.1.0